### ISSUE TITLE
bug(3.0.1): grunt-cwebp 3.0.1 doesn’t convert images to webp dynamically

### ISSUE THREAD

**Issue by Kristinita** [1000ch/grunt-cwebp#14]
### 1. Summary

See issue header.

grunt-cwebp 2.1.1 works as expected.

### 2. MCVE

You can see it in [**`KiraCWebpDynamic` branch**](https://github.com/Kristinita/SashaGruntDebugging/tree/KiraCWebpDynamic) of my repository for debugging.

#### 2.1. Environment

1. Ubuntu 20.04.1 LTS
1. Node.js 14.11.0
1. grunt 1.3.0
1. grunt-cli 1.3.2
1. grunt-cwebp 3.0.1

#### 2.2. Gruntfile.coffee

```coffee
module.exports = (grunt) ->

    grunt.loadNpmTasks 'grunt-cwebp'
    grunt.initConfig
        cwebp:
            dynamic:
                files: [
                    expand: true
                    cwd: '.'
                    src: "NeliaAutumnLeaves.jpg"
                    dest: '.'
                ]

    return

```

#### 2.3. .travis.yml

```yaml
os: linux

dist: focal

git:
  depth: 1

language: node_js

node_js:
- node

install:
- npm install -g grunt-cli
- npm install

script:
- grunt cwebp --verbose

```

#### 3.1. Expected

**If** grunt-cwebp@2.1.1:

+ [**Travis**](https://travis-ci.org/github/Kristinita/SashaGruntDebugging/builds/728341898#L245):

    ```text
    ✔ NeliaAutumnLeaves.jpg was converted to NeliaAutumnLeaves.webp
    ```

#### 3.2. Current

**Else** 3.0.1:

+ [**Travis**](https://travis-ci.org/github/Kristinita/SashaGruntDebugging/builds/728344860):

`NeliaAutumnLeaves.jpg` not converted to `NeliaAutumnLeaves.webp`.

Thanks.
